# Generated by Django 3.0.6 on 2020-05-21 13:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False, verbose_name='Принято к заказу')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=100, verbose_name='url')),
                ('description', models.TextField(blank=True, default='Описание категории', max_length=1000, verbose_name='Описание категории')),
                ('published', models.BooleanField(default=0, verbose_name='Отображение категории')),
                ('sort', models.PositiveIntegerField(default=10, verbose_name='Сортировка по приоритету')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Child_category', to='app.Category', verbose_name='Parent_category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=1000)),
                ('manufacturer', models.TextField(max_length=1000)),
                ('issue_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('sort', models.PositiveIntegerField(default=10, verbose_name='Сортировка по приоритету')),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата публикации')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='goods/', verbose_name='Изображения')),
                ('left', models.PositiveIntegerField(default=0, verbose_name='Остаточнок количество')),
                ('description', models.TextField(max_length=1000)),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('discount', models.PositiveSmallIntegerField(default=0, verbose_name='Скидка')),
                ('slug', models.SlugField(max_length=30, verbose_name='url')),
                ('short_text', models.CharField(max_length=100, null=True, verbose_name='Краткое описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название промо кода')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание промо кода')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата истечения действия')),
                ('discount_value', models.SmallIntegerField(default=0, verbose_name='Скидка')),
            ],
            options={
                'verbose_name': 'Промо код',
                'verbose_name_plural': 'Промо коды',
                'ordering': ['-expiration_date'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('text', models.TextField(max_length=3000)),
                ('short_text', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Краткое описание')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=15, unique=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post/', verbose_name='Изображения')),
                ('edit_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата редактирования')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликован?')),
                ('viewed', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('status', models.BooleanField(default=False, verbose_name='Для зарегистрированных')),
                ('sort', models.PositiveIntegerField(default=10, verbose_name='Сортировка по приоритету')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': ('Пост',),
                'verbose_name_plural': 'Посты',
                'ordering': ['sort', '-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000, null=True, verbose_name='Комментарий к заказу')),
                ('done', models.BooleanField(default=False, verbose_name='Заказ выполнен')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заказа')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Итоговая сумма заказа')),
                ('receiver_name', models.CharField(max_length=70, null=True, verbose_name='Имя и отчетство получателя')),
                ('receiver_surname', models.CharField(max_length=100, null=True, verbose_name='Фамилия')),
                ('receiver_mail', models.EmailField(max_length=254, null=True, verbose_name='Почта получателя')),
                ('is_save_info', models.BooleanField(default=False, verbose_name='Сохранить информацию заказа')),
                ('delivery_address', models.CharField(max_length=1000, null=True, verbose_name='Адрес доставки')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cart', verbose_name='Корзина')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['cart'],
            },
        ),
        migrations.CreateModel(
            name='GoodsInCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Единиц товара')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Общая сумма')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_cart', to='app.Cart', verbose_name='Товар в корзине')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cart_goods', to='app.Goods', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Товары в корзине',
                'ordering': ['cart'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='В избранном у пользователя')),
                ('good', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Goods', verbose_name='Товар в избранном')),
            ],
            options={
                'verbose_name': 'Избранный товар',
                'verbose_name_plural': 'Избранные товары',
                'ordering': ['-client'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('moderation', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('child_comment', models.ManyToManyField(blank=True, related_name='_comment_child_comment_+', to='app.Comment', verbose_name='Дочерний комментарий')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Post', verbose_name='Посты')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['author'],
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount', to='app.PromoCode'),
        ),
        migrations.AddConstraint(
            model_name='goodsincart',
            constraint=models.UniqueConstraint(fields=('good', 'cart'), name='goods unique'),
        ),
    ]
