# Generated by Django 3.0.3 on 2020-03-19 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=100, verbose_name='url')),
                ('description', models.TextField(blank=True, default='Описание категории', max_length=1000, verbose_name='Описание категории')),
                ('published', models.BooleanField(default=0, verbose_name='Отображение категории')),
                ('sort', models.PositiveIntegerField(default=10, verbose_name='Сортировка по приоритету')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Child_category', to='app.Category', verbose_name='Parent_category')),
            ],
            options={
                'verbose_name': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('text', models.TextField(max_length=3000)),
                ('subtitle', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Краткое описание')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=15, unique=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post/', verbose_name='Изображения')),
                ('edit_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата редактирования')),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата публикации')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликован?')),
                ('viewed', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('status', models.BooleanField(default=False, verbose_name='Для зарегистрированных')),
                ('sort', models.PositiveIntegerField(default=10, verbose_name='Сортировка по приоритету')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': ('POST',),
                'ordering': ['sort', '-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=1000)),
                ('manufacturer', models.TextField(max_length=1000)),
                ('sort', models.PositiveIntegerField(default=10, verbose_name='Сортировка по приоритету')),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата публикации')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='goods/', verbose_name='Изображения')),
                ('left', models.PositiveIntegerField(default=0, verbose_name='Остаточнок количество')),
                ('description', models.TextField(max_length=1000)),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('slug', models.SlugField(max_length=30, verbose_name='url')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('moderation', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Post', verbose_name='Посты')),
            ],
            options={
                'verbose_name': 'Комментарии',
            },
        ),
    ]
