# Generated by Django 3.0.3 on 2020-04-01 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200329_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['sort', '-created_date'], 'verbose_name': ('Пост',), 'verbose_name_plural': 'Посты'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
