# Generated by Django 3.0.3 on 2020-04-02 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200401_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название промо кода')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание промо кода')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateTimeField(verbose_name='Дата истечения действия')),
                ('discount_value', models.SmallIntegerField(default=0, verbose_name='Размер скидки в %')),
                ('goods', models.ManyToManyField(related_name='promo_goods', to='app.Goods', verbose_name='Промо код для товара')),
            ],
        ),
    ]
