# Generated by Django 3.0.3 on 2020-04-05 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_promocode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['-expiration_date'], 'verbose_name': 'Промо код', 'verbose_name_plural': 'Промо коды'},
        ),
        migrations.CreateModel(
            name='FavoriteGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='В избранном у пользователя')),
                ('good', models.ManyToManyField(to='app.Goods', verbose_name='Товар в избранном')),
            ],
            options={
                'verbose_name': ('Избранный товар',),
                'verbose_name_plural': ('Избранные товары',),
            },
        ),
    ]
