# Generated by Django 3.0.3 on 2020-04-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200410_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['-id'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='goods',
            name='short_text',
            field=models.CharField(max_length=100, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='goodsincart',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Единиц товара'),
        ),
    ]
