# Generated by Django 3.0.3 on 2020-04-14 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200412_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsincart',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='goods_in_cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.GoodsInCart', verbose_name='Товары в корзине'),
        ),
    ]
