# Generated by Django 3.0.3 on 2020-04-14 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200414_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='goods_in_cart',
        ),
        migrations.AddField(
            model_name='goodsincart',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cart', verbose_name='Товар в корзине'),
        ),
    ]
