# Generated by Django 3.0.3 on 2020-04-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_comment_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsincart',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Единиц товара'),
        ),
    ]
