# Generated by Django 3.0.3 on 2020-04-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200422_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_comment',
            new_name='child_comment',
        ),
    ]
